### PR TITLE
this.nodes as an object instead of sparse array

### PR DESCRIPTION
**Pull request by mattsgarlata**
allows for more efficient iteration over the elements

### CODE REVIEW

**Comment by mattsgarlata** [comment]
I needed to iterate over a tree with just 5 elements in it, but I discovered that `tree.nodes` was a sparse array instead of an Object. See below:

Screen Shot 2020-08-07 at 5 34 42 AM

I don't know if there's some fancy way to iterate over just the populated elements of a sparse array rather than having to iterate overall the indices. Either way, I think it would be a more natural expression of what the data structure holds to define it as an object rather than array since it functions more like a hash than an array. In this example maybe iterating over 192 elements wouldn't matter. However, at SMS we have trees with IDs stretching into the hundreds of thousands so it would make a difference for them.

If you agree with this change, I wonder if `this._layout` should also be defined as `{}` instead of `[]`

**Comment by mattsgarlata** [comment]
Oh, I tried to npm link in this change to try it out, but it didn't work :( I couldn't find my notes on how to npm link. It's been a long time

**Comment by nathanbowser** [comment]
I tested this in the tree, and tests pass. This is fine. _layout needs to be an array though.

**Comment by nathanbowser** [comment]
@mattsgarlata I'll bump the tree in impact. What branch?

**Comment by mattsgarlata** [comment]
`release-2020-sms-summer` please. Thank you!

**Pull request merged**
