### PR TITLE
Adds `expandedNodes` method to the tree.

### LINKED ISSUE #448: Tree state
Talked to @jerryorr and he needs the ability to persist the state. We'll add something like `getExpandedNodes` which can be used on a future tree render.

### PR DESCRIPTION
**Pull request by nathanbowser**
This returns all the nodes that are expanded.

Fixes #448

### CODE REVIEW

**Comment by nathanbowser** [comment]
@jerryorr This is part one of your request from our slack chat early. Do you want the ability to set some state on the incoming nodes so the tree is rendered correctly, or do you want to render and then expand each of these nodes you persisted?

**Comment by mattsgarlata** [comment]
@nathanbowser for a very large tree, I would think manually expanding the nodes would be really slow, wouldn't it?

**Comment by nathanbowser** [comment]
Yea good point. I'll add support for initial renders because we already performance tune the drawing.

**Comment by nathanbowser** [comment]
Updated.

@jerryorr You can set `collapsed: false` on any of the persisted nodes that should be expanded on initial render.

I am thinking collapsed: false might seem weird, but that follows the internal conventions used by the tree, so I stuck with it.

**Comment by mattsgarlata** [comment]
+1

**Pull request merged**
