### PR TITLE
Removes `moz` styles prefix for firefox

### PR DESCRIPTION
**Pull request by nathanbowser**
Apparently no longer needed (or supported)

For https://github.com/SpiderStrategies/Scoreboard/issues/58126

### CODE REVIEW

**Comment by mattsgarlata** [comment]
Will this break backward compatibility with old versions of Firefox? We aren't required to support old versions, but if it's easy to maintain compatibility with both, that would be nice.

**Comment by nathanbowser** [comment]
@derekstory I just found a `moz` prefix in the css, going to test another commit in a moment.

**Comment by nathanbowser** [comment]
> Will this break backward compatibility with old versions of Firefox? We aren't required to support old versions, but if it's easy to maintain compatibility with both, that would be nice.

@mattsgarlata Good question. I suspect these prefixes aren't needed. They were historically added for experimental features but this stuff is way way way past the experimental days. But I'll check b/c I'm going to make one more change to css.

**Review by derekstory — APPROVED** [review]
+1 Working for me in FF

**Comment by nathanbowser** [comment]
@mattsgarlata Jerry confirmed < 126 is working

https://spiderstrategies.slack.com/archives/C02N7NPRX/p1716313245948109?thread_ts=1716313176.269269&cid=C02N7NPRX

**Pull request merged**
