### PR TITLE
Tree fires `rendered` event once the initial render has completed and

### PR DESCRIPTION
**Pull request by nathanbowser**
all visible nodes have been drawn.

For https://github.com/SpiderStrategies/Scoreboard/issues/22903

### CODE REVIEW

**Comment by nathanbowser** [comment]
@mattsgarlata This will fire a `rendered` event on the tree once the nodes are in the DOM. 

In your original writeup in SB3, you said:

> It would be nice if there was a clean way in the tree API to know when it's safe to interact with the tree and be assured that calls to tree.get will return the nodes in the tree.

I don't see how a `tree.get(...)` call would fail if you're already waiting on the tree's stream `end` event.

**Comment by mattsgarlata** [comment]
Haha, looks like the tree code itself kind of needed this event for its own purposes!

As far as `tree.get` not working, my suspicion is that it has to do with the order in which events are setup. I'm sending a stream to the tree, and on that stream I setup all my event handlers to run. Then the tree is created and it tacks on its event handlers, but those would get invoked AFTER my event handlers. I guess I should probably just attach my events AFTER the tree is constructed so the tree can do its thing first.

+1

**Comment by mattsgarlata** [comment]
Are you going to give this a different version numbering scheme since it goes into 3.3 instead of 3.2.8 in Scoreboard?

**Comment by nathanbowser** [comment]
I was going to give it a minor bump instead of patch. I wasn't planning on bumping the tree version in 3.2.8. What would you like?

**Comment by mattsgarlata** [comment]
I think we should bump the version to 2.20.0 with this change. That way we'll always know Scoreboard 3.2.8 is on 2.19.x and Scoreboard 3.3+ are on 2.20.x+

**Comment by nathanbowser** [comment]
We're on the same page. That's exactly what I had planned.

**Pull request merged**
