### PR TITLE
Rtl changes

### PR DESCRIPTION
**Pull request by malik-habib**
Switched to using logical properties and adjusted the tree for RTL

### CODE REVIEW

**Comment by nathanbowser** [comment]
@malik-habib The JS blocks you modified are repeated a few times. What do you think about storing the RTL direction in the as a property of the tree?

Off the top of my head, maybe in `defaults`? e.g. https://github.com/SpiderStrategies/kalpa-tree/blob/master/index.js#L100

Then I'd consider maybe adding some kind of a transformation function that always modifies `x` based on the RTL direction. I think it'd clean up a lot of repeated code.

If you want to brainstorm a little or disagree, I'm all ears.

**Comment by nathanbowser** [comment]
Oh yea and can you please write a test for the RTL changes? The tree code is ~100% test coverage b/c it's such an essential component of Impact and I'd like to make sure test coverage stays high. I think this should be easy to test.

**Comment by mattsgarlata** [comment]
@malik-habib, @nathanbowser will link an existing test that should be similar to what you need to write to make things easier.

**Comment by malik-habib** [comment]
@nathanbowser I like the idea, I'm looking into implementing it

**Comment by mattsgarlata** [comment]
@nathanbowser would you mind posting a similar test for Ahmed to look at? It's holding up his work.

**Comment by mattsgarlata** [comment]
Thanks @nathanbowser!

**Comment by malik-habib** [comment]
I don't have any more commits pending here

**Comment by mattsgarlata** [comment]
+1

**Comment by malik-habib** [comment]
I just noticed something here. I'm making one new commit

**Comment by nathanbowser** [comment]
The tests are failing in this branch for me. Are they working for you when you run `npm t`? @malik-habib

**Comment by malik-habib** [comment]
@nathanbowser Yeah, they're both passing for me?

**Comment by nathanbowser** [comment]
Run `npm test` without any `.only` so the entire suite runs. Does it pass?

**Comment by malik-habib** [comment]
I see the issue now. Working on this

**Comment by malik-habib** [comment]
@nathanbowser I tweaked my tests and they pass but could you help me figure out where the cause of this failure? 
image

**Comment by mattsgarlata** [comment]
Thanks @malik-habib @nathanbowser!

**Pull request merged**
