### PR TITLE
use a default color scheme if user doesn't have access to scoreboard-colors

### PR DESCRIPTION
**Pull request by dankolz**
This worked so great I wanted to use it in a project. However, it had a dependency on a Spider Strategies only module. I don't know if you guys want it, but I modified the project so that it would optionally install the scoreboard-colors dependency and would build without it, if it wasn't available.

### CODE REVIEW

**Comment by mattsgarlata** [comment]
Hi @dankolz! Good to hear from you!

I am a little confused. Is the scoreboard-colors project not publicly available? It looks to me as though it is. If it is publicly available, would that also address your concern here?

**Comment by nathanbowser** [comment]
@mattsgarlata is correct. We made scoreboard-colors public awhile ago. I bet we just need to change the protocol to use https instead of ssh here: https://github.com/SpiderStrategies/kalpa-tree/blob/master/package.json#L12

**Comment by dankolz** [comment]
Good to talk to you guys as well!

Yes, if scoreboard-colors was downloadable via the http mechanism, that would also work for me.

**Comment by nathanbowser** [comment]
@dankolz Nice seeing your name pop up on our github. Hope all is well.

I just changed the protocol to git+https and published   v3.3.2. Hope that works for you!

**Pull request closed without merging**
