### PR TITLE
Forces hardware accelation by using `translate3d`.

### PR DESCRIPTION
**Pull request by nathanbowser**
See https://github.com/SpiderStrategies/Scoreboard/issues/9792 for more
details and dialog.

### CODE REVIEW

**Comment by mattsgarlata** [comment]
@dankolz didn't we run into some issue with translate3d at some point?  Please review this PR and let us know your thoughts.

From me, +1

**Comment by nathanbowser** [comment]
@mattsgarlata Not sure if you're thinking of this issue: https://github.com/SpiderStrategies/Scoreboard/issues/9031

I remembered that issue and went back to track down history. I verified this is working fine with the translate3d (checked tree and SB3 in chrome, safari, FF, ios safari, and IE11). The previous cause was from this: https://github.com/SpiderStrategies/Scoreboard/commit/8647ad0fb0fcc75078a4227e570be0d9bb6f7191

Of course you could be thinking of something else entirely, and if so @dankolz can refresh both of our memories.

**Comment by mattsgarlata** [comment]
That's probably what I was thinking of

**Comment by nathanbowser** [comment]
Cool. I'm going to merge. If @dankolz has issues, I'll reopen.

**Comment by dankolz** [comment]
There are two possible problems that I remember with translate3d. 

One is that if you put it on too many elements it will decrease performance. Ideally you'd just put it panes within the application that get drawn/scrolled independently of each other. I bet it takes a lot to make a problem though. Thousands for a serious computer.

The second problem I found was with the "fixed" layout. iirc, it was tough to make something inside an element that had the translate3d applied to it behave correctly if it extended outside the transformed element. So, anything fixed would be a problem, but also (I think) absolutely placed items that extended outside. This is the kind of problem you notice at once though since layout techniques that should be working just stop.

**Comment by mattsgarlata** [comment]
@nathanbowser did you apply the translate-3d to a container or to some element that's repeated for each node in the tree?  Did you test this out with a huge tree to see if there was a performance regression?

**Comment by nathanbowser** [comment]
We were already using translate for the node and node-contents positioning. Based on my research, it seems like this should be an improvement, not a regression. If we run into issues, then I'll look into other options.

**Pull request merged**
